//created on: Apr 16, 2017
package com.trucutru
 import java.util.ArrayList;  
 import java.util.List;
import com.trucutru.model.*;

rule "Insertar datos"
	when
	then
		insert(new Materia("Mates",7));
end

rule "Calcular promedio global -> en cadena se obtiene el promedio de tareas por tema por materia por cada una en la lista de materias"
    //include attributes such as "salience" here...
    salience 100
    when
        $e : Estudiante($materias : materiasCursando);
    then
    	$e.setPromedioGlobal($e.getPromedioTotal($materias));
        System.out.println("Estudiante encontrado!!: " + $e.toString());
end

rule "Encontrar temas"
	when
		$e : Estudiante( $materias : materiasCursando );
		$mat : Materia() from $materias;
		$temas : Tema() from $mat.getTemas();
		$t : Tema(nombre == "MRUA") from $temas;
	then
		System.out.println("Se encontro: " + $t.getNombre());
end

rule "Mal historial, reprobando materia media-alta, pero con tiempo"
	when
		$e : Estudiante( $materias : materiasCursando );
		$mat : Materia() from $materias;
		eval($mat.getPromedioAlumno() < 60 
		&& ($mat.getNivelCurso() > 5 && $mat.getNivelCurso() < 8) 
		&& $mat.getPorcentajeCompl() < 50 
		&& $e.getPromedioGlobal() < 65 );
	then
		System.out.println($e.getNombre() + ", tu historial es malo, tu promedio en la materia: " + $mat.getNombre() + " es reprobatorio y el nivel de la clase es medio-alto; pero todavía tienes tiempo, busca asesoria");
end

rule "Buen historial, reprobando materia media-alta, pero con tiempo"
	when
		$e : Estudiante( $materias : materiasCursando );
		$mat : Materia() from $materias;
		eval($mat.getPromedioAlumno() < 60 
		&& ($mat.getNivelCurso() > 5 && $mat.getNivelCurso() < 8) 
		&& $mat.getPorcentajeCompl() < 50 
		&& $e.getPromedioGlobal() > 75 );
	then
		System.out.println($e.getNombre() + ", tu historial es bueno, tu promedio en la materia: " + $mat.getNombre() + " es reprobatorio y el nivel de la clase es medio-alto; pero todavía tienes tiempo, practica y ponte al corriente");
end
/*
rule "Inscripcion futura nivel correcto"
	when
		$e : Estudiante( promedioGlobal > 85
		&& materiaCursando.getNivelCurso() > 7 );
	then
		System.out.println($e.getNombre() + ", la materia: " + $e.getMateriaCursando().getNombre() + ", es perfecta para tu nivel");
end

rule "Inscripcion futura nivel bajo"
	when
		$e : Estudiante( promedioGlobal > 85
		&& materiaCursando.getNivelCurso() < 3 );
	then
		System.out.println($e.getNombre() + ", la materia: " + $e.getMateriaCursando().getNombre() + ", es muy baja para tu nivel");
end
*/
