package com.trucutru;
import com.trucutru.model.*;

/*rule "Mete usuario default"
	when
	then
		insert(new User("salaboy", 32));
end*/

rule "Category By Age: Adult"
    when
        $u: User( age >= 18, category == null ||  == "")
    then
    	System.out.println("Es adutlo");
        $u.setCategory("Adult");
end

rule "Category By Age: Teenager"
    when
        $u: User( age >= 12 && < 18, category == null || == "")
    then
        $u.setCategory("Teenager");
        System.out.println("Es teenager");
end

rule "Category By Age: Children"
    when
        $u: User( age < 12 && >= 0, category == null || == "")
    then
        $u.setCategory("Children");
        System.out.println("Es nino");
end

rule "Category By Age: Not Valid"
    when
        $u: User( age < 0, category == null || == "")
    then
        $u.setCategory("Not Valid");
        System.out.println("Es invalido");
end

rule "Hermano"
     when
		$pa1 : Padre()
		$pa2 : Padre($pa1.padre == padre && $pa1.hijo != hijo)
     then
		insert(new Hermano($pa1.getHijo(), $pa2.getHijo()));
		System.out.println("hermano insertado");
end

rule "Abuelo"
	when
		$p : Padre()
		$p1 : Padre($p.getHijo() == $p1.getPadre())
		//$p1 : Padre()
		//eval($p.getHijo() == $p1.getPadre())
	then
		insert(new Abuelo($p.getPadre(), $p1.getHijo()));
		System.out.println("abuelo insertado");
end

rule "Ancestro nivel 1 = padres"
	when
		$p : Padre()
	then
		insert(new Ancestro($p.getPadre(), $p.getHijo()));
		System.out.println("ancestro 1 insertado");
end

rule "Ancestro nivel 2 = abuelos"
	when
		$abu : Abuelo()
	then
		insert(new Ancestro($abu.getPadre(), $abu.getNieto()));
		System.out.println("ancestro 2 insertado");
end

rule "Ancestro nivel 2+"
	when
		$p : Padre()
		$a : Ancestro($p.hijo == ancestro)
	then
		insert(new Ancestro($p.getPadre(), $a.getDescendiente()));
		System.out.println("ancestro 2+ insertado");
end
